CREATE TABLE PRODUCT (
    ITEM_NAME VARCHAR2(50) NOT NULL,
    PRICE NUMBER(30, 2) NOT NULL,
    QUANTITY NUMBER(30) NOT NULL,
    COMMISSION NUMBER(5, 2) NOT NULL,
    SELLER_ID VARCHAR2(50),
    REGDATE DATE DEFAULT SYSDATE NOT NULL,
    MODDATE DATE DEFAULT NULL
); 

INSERT INTO PRODUCT (
    ITEM_NAME
    , PRICE
    , QUANTITY
    , COMMISSION
    , SELLER_ID
    , REGDATE )
VALUES (
     '아이폰'
    , 10000 
    , 10
    , 0.01
    , 's'
    , to_char(sysdate,'yyyy-mm-dd'));
    
SELECT 
     ITEM_NAME
    , PRICE
    , QUANTITY
    , COMMISSION
    , SELLER_ID
    , REGDATE
FROM PRODUCT 
WHERE SELLER_ID ='s';